/* Child-first reader. Reuses this page's existing story text and vector art.
 * No speech recognition, upload, fabricated language scores, or camera access. */
(()=>{
 'use strict';
 const KEY='englishStoryChildV1',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let saved={books:{},last:null},screen='shelf',generation=0,auto=false,utterance=null,speechTimer=null,nextTimer=null,rate=.85;
 let stream=null,recorder=null,requestEpoch=0,pending=false,recorded=null,recordUrl=null,recordMs=0,recordStarted=0,recordTimer=null;
 let activeMs=0,lastActive=performance.now(),restUntil=0,restInterval=null,quizWrong=0,quizWait=0;
 try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x&&x.books&&typeof x.books==='object'&&!Array.isArray(x.books)){saved=x;saved.last=STORIES.some(s=>s.id===x.last)?x.last:null}}catch(_){}
 const questions={
  'can-i-play-too':{q:'Who wants to join the game?',cn:'谁想加入游戏？',options:[['🐶','Puppy'],['🐍','Snake'],['🐱','Cat']],answer:1,hint:'看第5句：小蛇问“Can I play too?”',line:4},
  'my-new-toy':{q:'What do the friends fix?',cn:'朋友们一起修什么？',options:[['🧸','A toy'],['🚗','A car'],['🏠','A house']],answer:0,hint:'看结尾：两位朋友一起修好了玩具。',line:12},
  'i-broke-my-trunk':{q:'What did Gerald lift first?',cn:'Gerald先举起了什么？',options:[['🐈','A cat'],['🐕','A dog'],['🦛','A hippo']],answer:2,hint:'看第5句：First, I lifted a hippo…',line:4},
  'happy-pig-day':{q:'How does Gerald feel at first?',cn:'Gerald开始时是什么心情？',options:[['😡','Angry'],['😢','Sad'],['😴','Sleepy']],answer:1,hint:'看第6句：I feel a little sad today.',line:5},
  'i-am-invited-to-a-party':{q:'Where are the friends going?',cn:'朋友们要去哪里？',options:[['🎉','A party'],['🏫','A school'],['🏖️','A beach']],answer:0,hint:'看第1句：I am invited to a party!',line:0},
  'should-i-share-my-ice-cream':{q:'What does Gerald share?',cn:'Gerald分享了什么？',options:[['🍎','An apple'],['🍰','A cake'],['🍦','Ice cream']],answer:2,hint:'看第11句：Would you like some ice cream?',line:10}
 };
 function persist(){try{localStorage.setItem(KEY,JSON.stringify(saved));return true}catch(_){notice('本机暂时无法保存进度，仍可以继续阅读。');return false}}
 function bookState(){const id=state.story.id;let b=saved.books[id];if(!b||typeof b!=='object'||Array.isArray(b))b=saved.books[id]={};b.line=Number.isInteger(b.line)?Math.max(0,Math.min(state.story.script.length-1,b.line)):0;b.heard=Array.isArray(b.heard)?[...new Set(b.heard.filter(n=>Number.isInteger(n)&&n>=0&&n<state.story.script.length))]:[];return b}
 function notice(text){const el=document.getElementById('kidStatus');if(el)el.textContent=text}
 function btn(action,text,cls='',extra=''){return `<button type="button" class="kid-btn ${cls}" data-action="${action}" ${extra}>${text}</button>`}
 function panels(view){screen=view;['shelf','reader','quiz','retell'].forEach(id=>document.getElementById('kid-'+id).hidden=id!==view);document.getElementById('kidBack').textContent=view==='shelf'?'← 学习首页':'← 返回书架';document.getElementById('kidBack').href=view==='shelf'?'/':'#shelf';window.scrollTo({top:0,behavior:'auto'})}
 document.getElementById('app').innerHTML=`<header class="kid-head"><a id="kidBack" href="/">← 学习首页</a><div class="kid-brand">📚 英语故事馆</div><span class="kid-count" id="kidCount"></span></header><main><section id="kid-shelf"></section><section id="kid-reader" hidden></section><section id="kid-quiz" hidden></section><section id="kid-retell" hidden></section><p id="kidStatus" class="kid-status" role="status" aria-live="polite"></p><details class="kid-help"><summary>家长陪读 · 声音与隐私说明</summary><p>先听一句，再指图说一句；用中文、英文或混合表达都可以。不要求孩子讲满7分钟。</p><p>本页保留原有的小猪小象主题改写练习，不是出版绘本原文，也未声明取得出版社授权。理解题仅针对本页版本，不用于教材同步或商业授权证明。</p><p>朗读使用设备提供的英语语音，音色和可用性因设备而异；不声称真人录音或已获发音认证。没有英语语音时请由家长陪读，不会用中文声音代读。</p><p>进度仅存于当前浏览器。录音需要明确勾选家长同意，仅申请麦克风，不申请摄像头；录音只在内存中，不上传。刷新会丢失未下载录音。页面不分析发音、词汇或故事完整度，不给虚假的语言能力分。</p><p>约10分钟前台阅读后提醒休息1分钟；这只是使用提醒，不替代家长安排。</p></details></main><div class="kid-rest" id="kidRest" role="dialog" aria-modal="true" aria-labelledby="kidRestTitle" hidden><section><div style="font-size:64px">🌳</div><h2 id="kidRestTitle">眼睛去散散步</h2><p>看看远处，伸伸小手。<br>故事会在这里等你。</p><p id="kidRestTime"></p>${btn('rest','休息后继续','primary','id="kidRestContinue" disabled')}</section></div>`;
 function shelf(){stop();endRecording();panels('shelf');const colors=['#e4f3ff','#ffe8e9','#e8f2da','#ffeabf','#eee2fb','#e0f4f0'];const last=STORIES.find(s=>s.id===saved.last);document.getElementById('kid-shelf').innerHTML=`<section class="kid-hero"><div><span class="kid-eyebrow">每天一个小故事</span><h1>听故事，<br>交个新朋友。</h1><p>看一看 · 听一听 · 说一句</p><div class="kid-actions">${btn('open',last?'▶ 继续上次的故事':'▶ 从这个故事开始','primary',`data-id="${last?.id||STORIES[0].id}"`)}</div></div><div class="hero-art" aria-hidden="true">${coverArt(last||STORIES[0])}</div></section><div class="kid-section-head"><h2>今天想读哪一本？</h2><span>6个故事</span></div><div class="kid-books">${STORIES.map((s,i)=>{const b=saved.books[s.id],heard=Array.isArray(b?.heard)?b.heard.length:0;return `<button class="kid-book" data-action="open" data-id="${s.id}"><div class="kid-cover" style="--cover:${colors[i]}"><span>${i===0?'从这里开始':'故事 '+(i+1)}</span>${coverArt(s)}</div><h3>${esc(s.cn)}</h3><p lang="en">${esc(s.title)}</p><small>${b?.complete?'🌟 听完并答对':heard?`🎧 听过 ${heard} / ${s.script.length} 句`:`🎧 ${s.script.length} 句 · 可分次读`}</small></button>`}).join('')}</div>`;document.getElementById('kidCount').textContent='🌟 '+STORIES.filter(s=>saved.books[s.id]?.complete).length+' / 6';notice('选一本喜欢的故事，随时都能回来继续。')}
 function open(id){const story=STORIES.find(s=>s.id===id);if(!story)return;if(recorded&&state.story?.id!==id&&!confirm('换故事会清除尚未下载的录音，确定继续吗？'))return;stop();endRecording();if(state.story?.id!==id)clearRecording();state.story=story;state.lineIndex=bookState().line;state.showCn=false;saved.last=id;persist();_stageCache={scene:-1,pairKey:'',bubbleHtml:''};reader()}
 function reader(){stop();endRecording();panels('reader');document.getElementById('kid-reader').innerHTML=`<div class="kid-reader-head">${btn('shelf','← 书架')}<div><h1>${esc(state.story.cn)}</h1><p lang="en">${esc(state.story.title)}</p></div></div><div class="kid-reader-layout"><div class="stage" id="stage" role="img" aria-label="当前故事场景"></div><div class="kid-text"><div id="nowCard"></div><progress class="kid-progress" id="kidProgress"></progress><p class="kid-status" id="kidPage"></p></div></div><div class="kid-controls">${btn('prev','← 上一句','','id="kidPrev"')}${btn('listen','🔊 听这一句','primary')}${btn('next','下一句 →','','id="kidNext"')}</div><div class="kid-tools">${btn('auto','▶ 连续听','','id="kidAuto"')}${btn('translate','看中文','','id="kidTranslate" aria-pressed="false"')}<label>语速 <select id="kidRate"><option value="0.7">慢一点</option><option value="0.85">舒适</option><option value="1">正常</option></select></label></div><div class="kid-actions">${btn('quiz','🧩 想一想')}${btn('retell','🎙️ 我来说一句')}</div>`;document.getElementById('kidRate').value=String(rate);draw();notice('先听一句。看不懂时，再点“看中文”。')}
 window.renderNowCard=function(){const line=state.story.script[state.lineIndex],ch=CHARACTERS[line.who];document.getElementById('nowCard').innerHTML=`<p class="kid-speaker">${ch.em} ${esc(ch.name)}</p><p class="kid-sentence" lang="en">${esc(line.en)}</p><p class="kid-translation" ${state.showCn?'':'hidden'}>${esc(line.cn)}</p>`};
 function draw(){renderStage();const b=bookState();b.line=state.lineIndex;persist();document.getElementById('kidProgress').max=state.story.script.length;document.getElementById('kidProgress').value=b.heard.length;document.getElementById('kidPage').textContent=`第 ${state.lineIndex+1} / ${state.story.script.length} 句 · 已听完 ${b.heard.length} 句`;document.getElementById('kidPrev').disabled=state.lineIndex===0;document.getElementById('kidNext').disabled=state.lineIndex===state.story.script.length-1;const trans=document.getElementById('kidTranslate');trans.textContent=state.showCn?'收起中文':'看中文';trans.setAttribute('aria-pressed',String(state.showCn));const image=document.getElementById('stage');image.setAttribute('aria-label',state.story.scenes[sceneIndexOfLine(state.lineIndex)].cap)}
 function stop(){generation++;auto=false;clearTimeout(speechTimer);clearTimeout(nextTimer);try{synth?.cancel()}catch(_){}document.querySelectorAll('audio').forEach(a=>a.pause());utterance=null;document.body.classList.remove('kid-speaking');const a=document.getElementById('kidAuto');if(a)a.textContent='▶ 连续听'}
 window.stopAll=stop;window.playLine=function(i){if(screen!=='reader')return;move(i);listen(false)};
 function speakSafe(text,done){stopSpeechOnly();const voices=synth?.getVoices()?.filter(v=>/^en(?:[-_]|$)/i.test(v.lang))||[];if(!voices.length){stop();notice('没有可用的英语声音。请开启设备英语语音后重试，或请家长陪读。');return}
  const token=++generation,u=new SpeechSynthesisUtterance(text);utterance=u;u.lang=voices[0].lang;u.voice=voices.find(v=>v.localService)||voices[0];u.pitch=1;u.rate=rate;u.volume=1;
  const fail=()=>{if(token!==generation)return;stop();notice('声音没有播放成功。请重新点朗读按钮，不会自动跳过。')};u.onerror=fail;u.onstart=()=>{if(token===generation){document.body.classList.add('kid-speaking');notice('正在朗读…')}};u.onend=()=>{if(token!==generation)return;clearTimeout(speechTimer);utterance=null;document.body.classList.remove('kid-speaking');if(done)done(token);else notice('听完啦，可以再听一次。')};speechTimer=setTimeout(fail,25000);try{synth.speak(u)}catch(_){fail()}}
 function stopSpeechOnly(){generation++;clearTimeout(speechTimer);try{synth?.cancel()}catch(_){}document.body.classList.remove('kid-speaking')}
 function listen(continuous){if(restUntil>Date.now())return;auto=continuous;const id=state.story.id,index=state.lineIndex;const a=document.getElementById('kidAuto');if(a)a.textContent=auto?'⏸ 暂停连续听':'▶ 连续听';speakSafe(state.story.script[index].en,token=>{if(state.story.id!==id||screen!=='reader')return;const b=bookState();if(!b.heard.includes(index))b.heard.push(index);finishBook();draw();notice('听完啦。你也可以跟着说一句。');if(auto&&index<state.story.script.length-1)nextTimer=setTimeout(()=>{if(token===generation&&auto&&!document.hidden){state.lineIndex++;state.showCn=false;draw();listen(true)}},650);else if(auto){auto=false;document.getElementById('kidAuto').textContent='▶ 再听一遍';notice('这个故事听完啦，来“想一想”，不用马上再读一本。')}})}
 function move(i){stop();state.lineIndex=Math.max(0,Math.min(state.story.script.length-1,i));state.showCn=false;draw();notice('点“听这一句”听英语。')}
 function finishBook(){const b=bookState();if(b.heard.length===state.story.script.length&&b.quiz)b.complete=true;persist()}
 function quiz(){stop();endRecording();panels('quiz');const q=questions[state.story.id];document.getElementById('kid-quiz').innerHTML=`${btn('reader','← 回到故事')}<section class="kid-task"><h2>🧩 听懂故事了吗？</h2><p lang="en">${esc(q.q)}</p><p>${esc(q.cn)}</p><div class="kid-actions">${btn('question','🔊 听问题')}</div><div class="kid-choices">${q.options.map((x,i)=>`<div class="kid-choice" id="choice${i}"><button data-action="answer" data-index="${i}"><span class="emoji" aria-hidden="true">${x[0]}</span><span>${i+1}. ${esc(x[1])}</span></button>${btn('option','🔊 听选项','',`data-index="${i}" aria-label="听选项 ${i+1} ${esc(x[1])}"`)}</div>`).join('')}</div><p id="quizFeedback" role="status">想一想，再选一个答案。答错可以再试。</p><div class="kid-actions">${btn('hint','💡 回到提示句')}${btn('retell','🎙️ 我来说一句')}</div></section>`;syncQuiz()}
 function syncQuiz(){document.querySelectorAll('[data-action="answer"]').forEach(b=>b.disabled=Date.now()<quizWait)}
 function answer(i){if(Date.now()<quizWait)return;const q=questions[state.story.id],correct=i===q.answer,el=document.getElementById('choice'+i);el.classList.add(correct?'correct':'wrong');if(correct){bookState().quiz=true;finishBook();document.getElementById('quizFeedback').textContent='答对啦！你找到了故事里的线索。';quizWrong=0}else{quizWrong++;document.getElementById('quizFeedback').textContent='再想一想。'+q.hint;if(quizWrong>=3){quizWait=Date.now()+8000;syncQuiz();document.getElementById('quizFeedback').textContent='先停下来想一想。'+q.hint+' 8秒后再试，也可以回去听。';setTimeout(()=>{if(screen==='quiz'){syncQuiz();document.getElementById('quizFeedback').textContent=q.hint+' 现在可以再试啦。'}},8100);quizWrong=0}}}
 function retell(){stop();endRecording();panels('retell');document.getElementById('kid-retell').innerHTML=`${btn('reader','← 回到故事')}<section class="kid-task"><h2>🎙️ 轮到你讲啦</h2><p>一句也很棒。先告诉身边的大人，不录音也可以。</p><div class="kid-retell-prompts"><span>🐘 谁在故事里？</span><span>💬 发生了什么？</span><span>🌈 最后怎么样？</span></div><p class="kid-notice">录音是可选的，只留在本机。这里不会自动判断你的发音或给复述打分。</p><label class="kid-consent"><input type="checkbox" id="kidConsent">家长同意本次使用麦克风</label><div class="kid-record-time" id="kidRecordTime">00:00</div><div class="kid-actions">${btn('record','🎙️ 开始录音','primary','id="kidRecord"')}${btn('stoprecord','停止 / 取消','','id="kidStopRecord" disabled')}</div><p id="kidRecordStatus" class="kid-status" role="status">说完就停，最多录2分钟，不必凑时长。</p><audio id="kidPlayback" controls hidden></audio><div class="kid-actions">${btn('download','下载这段录音','','id="kidDownload" hidden')}${btn('discard','删除这段录音','','id="kidDiscard" hidden')}</div></section>`;recordUI();if(recordUrl)showRecording()}
 function clearRecording(){requestEpoch++;if(recordUrl)URL.revokeObjectURL(recordUrl);recordUrl=null;recorded=null;recordMs=0}
 function recordUI(){const b=document.getElementById('kidRecord'),s=document.getElementById('kidStopRecord');if(b){b.disabled=pending||recorder?.state==='recording';s.disabled=!pending&&recorder?.state!=='recording';document.getElementById('kidRecordTime').textContent=fmt(recordMs/1000)}}
 function recNotice(t){const el=document.getElementById('kidRecordStatus');if(el)el.textContent=t}
 async function record(){if(pending||recorder?.state==='recording'||restUntil>Date.now())return;if(!document.getElementById('kidConsent').checked){recNotice('请家长先阅读并勾选同意。');return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){recNotice('此浏览器无法录音。可以直接讲给身边的大人听。');return}if(recorded&&!confirm('重新录音会清除上一段未下载录音，确定吗？'))return;
  stop();document.getElementById('kidPlayback').pause();clearRecording();pending=true;const epoch=++requestEpoch;recordUI();recNotice('请在浏览器提示中允许麦克风，也可以取消。');let acquired;
  try{acquired=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true},video:false});if(epoch!==requestEpoch||screen!=='retell'||document.hidden){acquired.getTracks().forEach(t=>t.stop());return}stream=acquired;const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(t=>MediaRecorder.isTypeSupported(t));const r=mime?new MediaRecorder(stream,{mimeType:mime}):new MediaRecorder(stream),chunks=[];recorder=r;pending=false;
   r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};r.onstop=()=>{if(epoch!==requestEpoch)return;recorded=new Blob(chunks,{type:r.mimeType||'audio/webm'});if(recorded.size){recordUrl=URL.createObjectURL(recorded);showRecording()}else recNotice('没有录到声音文件，请重试。')};r.onerror=()=>{endRecording();recNotice('录音中断了，可以重新录制。')};r.start(250);recordStarted=performance.now();recordTimer=setInterval(()=>{recordMs=Math.min(120000,performance.now()-recordStarted);recordUI();if(recordMs>=120000)endRecording()},200);recordUI();recNotice('正在录音，说完就点停止。')
  }catch(_){acquired?.getTracks().forEach(t=>t.stop());if(epoch!==requestEpoch)return;pending=false;stream=null;recorder=null;recordUI();recNotice('未能开启麦克风。可以重试，也可以直接讲给家长听。')}}
 function endRecording(){if(pending){requestEpoch++;pending=false}if(recorder?.state==='recording'){recordMs=Math.min(120000,performance.now()-recordStarted);recorder.stop()}clearInterval(recordTimer);stream?.getTracks().forEach(t=>t.stop());stream=null;recordUI()}
 function showRecording(){if(screen!=='retell'||!recordUrl)return;const a=document.getElementById('kidPlayback');a.src=recordUrl;a.hidden=false;document.getElementById('kidDownload').hidden=false;document.getElementById('kidDiscard').hidden=false;recNotice('录音已准备好。和家长一起听听：角色、事情、结尾，你讲到了哪些？不作自动评分。')}
 function download(){if(!recordUrl)return;const mime=recorded.type,ext=mime.includes('mp4')?'m4a':mime.includes('ogg')?'ogg':'webm';const a=document.createElement('a');a.href=recordUrl;a.download='my-story-'+state.story.id+'.'+ext;a.click();recNotice('已请求下载；是否保存成功，请在浏览器下载列表确认。')}
 function rest(){stop();endRecording();document.querySelectorAll('audio').forEach(a=>a.pause());restUntil=Date.now()+60000;const el=document.getElementById('kidRest');el.hidden=false;document.getElementById('kidRestContinue').disabled=true;const update=()=>{const left=Math.max(0,Math.ceil((restUntil-Date.now())/1000));document.getElementById('kidRestTime').textContent=left?'休息倒计时 '+left+' 秒':'休息好啦，准备好了再继续。';document.getElementById('kidRestContinue').disabled=left>0};update();clearInterval(restInterval);restInterval=setInterval(update,1000);document.getElementById('kidRestTitle').tabIndex=-1;document.getElementById('kidRestTitle').focus()}
 document.getElementById('app').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;if(restUntil>Date.now()&&a!=='rest')return;switch(a){case'open':open(b.dataset.id);break;case'shelf':shelf();break;case'reader':reader();break;case'prev':move(state.lineIndex-1);break;case'next':move(state.lineIndex+1);break;case'listen':stop();listen(false);break;case'auto':if(auto){stop();notice('已暂停，当前句子会保留。')}else listen(true);break;case'translate':state.showCn=!state.showCn;draw();break;case'quiz':quiz();break;case'question':speakSafe(questions[state.story.id].q);break;case'option':speakSafe(questions[state.story.id].options[+b.dataset.index][1]);break;case'answer':stop();answer(+b.dataset.index);break;case'hint':state.lineIndex=questions[state.story.id].line;reader();break;case'retell':retell();break;case'record':record();break;case'stoprecord':endRecording();break;case'download':download();break;case'discard':document.getElementById('kidPlayback').pause();document.getElementById('kidPlayback').removeAttribute('src');clearRecording();retell();break;case'rest':if(Date.now()>=restUntil){document.getElementById('kidRest').hidden=true;clearInterval(restInterval);activeMs=0;lastActive=performance.now();document.getElementById('kidBack').focus()}break}});
 document.getElementById('kidBack').addEventListener('click',e=>{if(screen!=='shelf'){e.preventDefault();shelf()}});
 document.addEventListener('change',e=>{if(e.target.id==='kidRate'){rate=Number(e.target.value);stop();notice('语速已调整，点“听这一句”重新听。')}});
 document.addEventListener('visibilitychange',()=>{lastActive=performance.now();if(document.hidden){stop();endRecording();document.querySelectorAll('audio').forEach(a=>a.pause())}});
 window.addEventListener('pagehide',()=>{stop();endRecording()});
 document.addEventListener('keydown',e=>{if(!document.getElementById('kidRest').hidden&&e.key==='Tab'){e.preventDefault();document.getElementById('kidRestContinue').focus()}});
 setInterval(()=>{const now=performance.now(),delta=now-lastActive;lastActive=now;if(!document.hidden&&screen!=='shelf'&&document.getElementById('kidRest').hidden&&delta<2000){activeMs+=delta;if(activeMs>=600000)rest()}},1000);
 // Exposed read-only diagnostics for acceptance; never grants completion.
 window.StoryChild={version:'story-child-v1',get screen(){return screen},get progress(){return JSON.parse(JSON.stringify(saved))}};
 shelf();
})();
